### ISSUE TITLE
Is it possible to dynamically set the currentLocale?

### ISSUE THREAD

**Issue by ceesvanegmond** [Prezent/doctrine-translatable-bundle#26]
Hi,

Is it possible to dynamically (manually) set the currentLocale in code withoug calling a `setCurrentLocale` in the entity manually?
In this case; i want to serialize an entity to a json file; and foreach json file I want another language to be active in the serialize process. 

The currentLocale is being set by the TranslateListener on request; but can I change the currentLocale in code too?

**Comment by sandermarechal** [comment]
> Is it possible to dynamically (manually) set the currentLocale in code without calling a setCurrentLocale in the entity manually?

This will not work the way you expect it to work. The currect locale is injected into the entity using Doctrine's postLoad event. If you serialize the same entity into multiple languages, the current locale will still not be updated because the entity is not reloaded.

You should be looking at your serialization system instead. Symfony has callbacks and normalizers. JMS Serializer has events and visitors. Use those to set the correct locale before serialization.

**Comment by ceesvanegmond** [comment]
Hi @sandermarechal ,

Thanks for your answer. Could you give me a hint on what to do? Using JMS This is what I have now:

```php
    // ArtSubscriber (Doctrine Subscriber)
    private function index(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();
        $artRepository = $args->getObjectManager()->getRepository(Art::class);

         if (! $entity instanceof Art) {
             return
         }

         // this locales = ['nl', 'en', 'de']
         foreach($this->locales as $locale) {
             $entity = $artRepository->getById($entity->getId())
             $this->artCollector->make($entity, $locale);
         }
        }
    }



    // ArtCollector.php
    public function make(Art $art, $locale)
    {
        $art->setCurrentLocale($locale);
      
        $jsonContent = $this->serializer->serialize($art, 'json', $this->getSerializeContext());
    }

    private function getSerializeContext() : SerializationContext
    {
        $context = new SerializationContext();
        $context->setSerializeNull(true);

        return $context;
    }
```

**Comment by sandermarechal** [comment]
To get rid of that `setCurrentLocale()` call there, you can use either the [JMS event](https://jmsyst.com/libs/serializer/master/event_system) system or a [custom handler](https://jmsyst.com/libs/serializer/master/handlers). Events are probably the easiest.

When using an event, call `setCurrentLocale()` from inside the `preSerialization` event handler in order to set the correct locale. E.g, something like:

```php
public function onPreSerialize(PreSerializeEvent $event) {
    if ($event->getObject() instanceof TranslatableInterface) {
        $event->getObject()->setCurrentLocale($this->getTheCorrectLocaleSomehow());
    }
}
```

**Comment by ceesvanegmond** [comment]
@sandermarechal Thanks!
